FlaskBlueprintsTemplate/FlaskBlueprintsTemplate/__init__.py
from flask import Flask
app = Flask(__name__)

from FlaskBlueprintsTemplate.domain.mod_test.views import test_module

# Register blueprints
app.register_blueprint(test_module)

FlaskBlueprintsTemplate/FlaskBlueprintsTemplate/domain/mod_test/views.py

from FlaskBlueprintsTemplate.framework.sql import sql_controller as sql
from datetime import datetime
from flask import render_template, Blueprint
test_module = Blueprint('test_module', __name__, template_folder='templates')

@test_module.route('/')
@test_module.route('/home')
def home():
    templateData = {
        'test': sql.test()
        }
    return render_template('index.html',**templateData)

@test_module.route('/contact')
def contact():
    """Renders the contact page."""
    return render_template(
        'contact.html',
        title='Contact',
        year=datetime.now().year,
        message='Your contact page.'
    )

@test_module.route('/about')
def about():
    """Renders the about page."""
    return render_template(
        'about.html',
        title='About',
        year=datetime.now().year,
        message='Your application description page.'
    )

FlaskBlueprintsTemplate/FlaskBlueprintsTemplate/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - My Flask Application</title>
    <link rel="stylesheet" type="text/css" href="/static/content/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="/static/content/site.css" />
    <script src="/static/scripts/modernizr-2.6.2.js"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">Application name</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('test_module.home') }}">Home</a></li>
                    <li><a href="{{ url_for('test_module.about') }}">About</a></li>
                    <li><a href="{{ url_for('test_module.contact') }}">Contact</a></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        {% block content %}{% endblock %}
        <hr />
        <footer>
            <p>&copy; {{ year }} - My Flask Application</p>
        </footer>
    </div>

    <script src="/static/scripts/jquery-1.10.2.js"></script>
    <script src="/static/scripts/bootstrap.js"></script>
    <script src="/static/scripts/respond.js"></script>
    {% block scripts %}{% endblock %}

</body>
</html>